[webservers]
prod-web-01 ansible_host=10.30.1.11 ansible_user=ansible ansible_connection=ssh os_family=Debian os_version=ubuntu22.04 patch_policy=standard
prod-web-02 ansible_host=10.30.1.12 ansible_user=ansible ansible_connection=ssh os_family=Debian os_version=ubuntu22.04 patch_policy=standard

[appservers]
prod-app-01 ansible_host=10.30.2.11 ansible_user=ansible ansible_connection=ssh os_family=Debian os_version=ubuntu22.04 patch_policy=standard
prod-app-02 ansible_host=10.30.2.12 ansible_user=ansible ansible_connection=ssh os_family=Debian os_version=ubuntu22.04 patch_policy=standard
